<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '723549da8909a836cd6f52bf483b4f3c',
  'DATABASE_NAME' => 'geneo',
  'DATABASE_USER' => 'symfony',
  'DATABASE_PASSWORD' => 'letmein',
  'DATABASE_ROOT_PASSWORD' => 'letmein',
  'DATABASE_URL' => 'DATABASE_URL="mysql://symfony:letmein@127.0.0.1:33068/geneo?serverVersion=8.0"',
);
