version: '3'
networks:
  backend:
    driver: bridge
services:
    php:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: geneo.app
        ports:
            - '43219:80'
        volumes:
            - ./:/var/www
            - ./logs/app/:/var/www/var/logs:cached
        depends_on:
            - db
        networks:
          - backend
    db:
      image: mysql:8.0
      container_name: geneo.db
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        - MYSQL_DATABASE=${DATABASE_NAME}
        - MYSQL_USER=${DATABASE_USER}
        - MYSQL_PASSWORD=${DATABASE_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      ports:
        - "33068:3306"
      volumes:
      - ./data/mysql:/var/lib/mysql
      networks:
      - backend