<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVe0ZexH\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVe0ZexH/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerVe0ZexH.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerVe0ZexH\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerVe0ZexH\srcApp_KernelProdContainer([
    'container.build_hash' => 'Ve0ZexH',
    'container.build_id' => '57682b38',
    'container.build_time' => 1615337378,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVe0ZexH');
