<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHxpz0tZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHxpz0tZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHxpz0tZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHxpz0tZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHxpz0tZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Hxpz0tZ',
    'container.build_id' => 'dbf75946',
    'container.build_time' => 1615336879,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHxpz0tZ');
