<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK4gkvxA\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK4gkvxA/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK4gkvxA.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK4gkvxA\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerK4gkvxA\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'K4gkvxA',
    'container.build_id' => '7e86b46e',
    'container.build_time' => 1615338806,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK4gkvxA');
